### ISSUE TITLE
Less of an issue...

### ISSUE THREAD

**Issue by davehodg** [houseabsolute/HTML-Mason#30]
Sorry we seem to have been quiet for a few months. 

I have a bunch of live MAson code which has no tests. I'm looking for examples of Mason tests, but the only tests I can find have add_test with the component inline. I can't see how to add a test to a file.

Halp?

**Comment by autarch** [comment]
Sorry for the slow response. Honestly, I haven't used Mason myself in ages. I just fix critical bugs in it these days.

You should be able to instantiate an Interp object with a Resolver and have it load components off the filesystem for tests.

**Comment by davehodg** [comment]
OK, I know those words, just not the order they've been used in. Got any examples of this on GitHub? Know anyone with public code doing it I can cargo-cult?

**Comment by autarch** [comment]
> OK, I know those words, just not the order they've been used in. Got any examples of this on GitHub? Know anyone with public code doing it I can cargo-cult?
> 
> Is HTML::Mason::Tests not worth looking at?

Look at whatever code executes your Mason templates. That will construct the same objects you'd want to use in your tests.
